name: Prep - Build Docker Image (on Dockerfile push)

# workflow is for a branch push only and ignores main.
# push to main (which is also pull request merge) has a more elaborate workflow to run
# github repo is configured with branch protection on main.
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/docker-node/*.Dockerfile'

  workflow_dispatch:

jobs:
  build-push:
    name: Build Docker Image
    runs-on: ubuntu-latest
    # github actions triggered by on push will be triggered by both branch and tag push.
    # the paths filter only applies to branch push and as a result the workflow will run on tag push.
    # adding tags-ignore: filter causes the workflow to not run at all.
    # add a conditional to prevent tag push runs.
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./.github/docker-node/
          file: ./.github/docker-node/node-agent-runner.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/node-agent-runner
