name: Release - NPM Publish (on push tag)

on: 
  workflow_dispatch:
    inputs: 
      releasing:
        required: true
        description: 'Version being released exactly as in package.json (11.2.1-prerelease.0)'

jobs:
  is-publishable:
    name: Check if package published
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check is publishable version
        run: .github/scripts/is-publishable.sh ${{ github.event.inputs.releasing }}

  npm-publish:
    name: NPM Publish
    runs-on: ubuntu-latest 
    needs: is-publishable

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Show Environment Info
        run: |
          printenv
          node --version
          npm --version 
          cat /etc/os-release
  
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'  # Setup .npmrc file to publish to npm

      # *** IMPORTANT: 
      # by default any package published to npm registry is tagged with 'latest'. to set other pass --tag. 
      # any pre-release package (has - in version), regardless of name defined with version preid, will be npm tagged with 'prerelease'.
      - name: NPM Publish (prerelease)
        run: npm publish --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: ${{ contains(github.event.inputs.releasing, '-') }}

      - name: NPM Publish (latest)
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: ${{ !contains(github.event.inputs.releasing, '-') }}
